import { Dimensions, StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';

export const styles = StyleSheet.create({
    screenContainer: {
        backgroundColor: 'white',
        width: Dimensions.get('window').width,
        height: Dimensions.get('window').height,
    },
    flex1: {flex: 1},
    backButton: {
        marginLeft: Dimensions.get('window').width * 0.05927,
        marginTop: 8,
        marginBottom: 65,
    },
    backIcon: {
        width: 10,
        height: 18,
    },
    title: {
        fontSize: RFValue(26, 1000),
        color: '#030303',
        fontWeight: '600',
        width: Dimensions.get('window').width * 0.536452,
        marginLeft: Dimensions.get('window').width * 0.05927,
        height: Dimensions.get('window').height * 0.07031,
    },
    description: {
        fontSize: RFValue(16, 896),
        color: '#7c7c7c',
        fontWeight: '600',
        marginLeft: Dimensions.get('window').width * 0.05927,
        marginTop: 27.58,
        marginBottom: 10,
    },
    flag: {
        width: Dimensions.get('window').width * 0.08208,
        height: Dimensions.get('window').height * 0.02645,
        marginRight: 12.02,
    },
    inputContainer: {
        width: Dimensions.get('window').width * 0.8795,
        height: Dimensions.get('window').height * 0.04414,
        alignSelf: 'center',
        borderBottomWidth: 1,
        borderColor: '#E2E2E2',
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 40,
        marginTop: 30.61,
    },
    input: {
        flex: 1,
        fontFamily: 'NotoSans-VariableFont_wdth,wght',
        fontSize: RFValue(18, 896),
        color: '#030303',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 0,
        margin: 0,
        lineHeight: 12,
        height: Dimensions.get('window').height * 0.032366,
    },
    bottomButtons: {
        position: 'absolute',
        bottom: 30,
        flexDirection: 'row',
        width: Dimensions.get('window').width * 0.8795,
        alignSelf: 'center',
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    resendCode: {},
    resendCodeText: {
        color: '#53B175',
        fontSize: RFValue(18, 896),
    },
    nextButton: {
        width: 67,
        height: 67,
        borderRadius: 35,
        backgroundColor: '#53B175',
        justifyContent: 'center',
        alignItems: 'center',
    },
    nextIcon: {
        width: 10,
        height: 18,
    },
});
